//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCSS.EntityModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVE
    {
        public LEAVE()
        {
            this.LEAVEMODIFies = new HashSet<LEAVEMODIFY>();
        }
    
        public int LeaveId { get; set; }
        public int LeaveTypeId { get; set; }
        public int LeaveStatusId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> DaysOff { get; set; }
        public string Reason { get; set; }
        public string RejectReason { get; set; }
    
        public virtual LEAVESTATU LEAVESTATU { get; set; }
        public virtual LEAVETYPE LEAVETYPE { get; set; }
        public virtual ICollection<LEAVEMODIFY> LEAVEMODIFies { get; set; }
    }
}
