//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCSS.EntityModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVEBALANCE
    {
        public int LeaveBalanceId { get; set; }
        public int UserId { get; set; }
        public int LeaveTypeId { get; set; }
        public Nullable<int> RemainingDays { get; set; }
    
        public virtual LEAVETYPE LEAVETYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
