//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCSS.EntityModel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCSSEntities : DbContext
    {
        public NCSSEntities()
            : base("name=NCSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ARTICLE> ARTICLEs { get; set; }
        public DbSet<EVENT> EVENTs { get; set; }
        public DbSet<LEAVE> LEAVEs { get; set; }
        public DbSet<LEAVEBALANCE> LEAVEBALANCEs { get; set; }
        public DbSet<LEAVEMODIFY> LEAVEMODIFies { get; set; }
        public DbSet<LEAVESTATU> LEAVESTATUS { get; set; }
        public DbSet<LEAVETYPE> LEAVETYPEs { get; set; }
        public DbSet<NEWS> NEWS { get; set; }
        public DbSet<PAYSLIP> PAYSLIPs { get; set; }
        public DbSet<ROLE> ROLEs { get; set; }
        public DbSet<USER> USERs { get; set; }
    }
}
